/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IPolls {
    function setRegistry(address registry) external;

    function createPoll(string calldata title) external returns (uint256);

    function vote(uint256 poll_id, bool support) external;

    function closePoll(uint256 poll_id) external;

    function getResults(uint256 poll_id) external view returns (uint256, uint256);

    function hasVoted(uint256 poll_id, address voter) external view returns (bool);

    function isActive(uint256 poll_id) external view returns (bool);

    function pollCount() external view returns (uint256);

    function getTitle(uint256 poll_id) external view returns (string memory);

    function registry() external view returns (address);

    function owner() external view returns (address);

    error PollNotFound(uint256);

    error PollNotActive(uint256);

    error VoterNotRegistered(address);

    error AlreadyVoted(uint256, address);

    error Unauthorized(address);

    error RegistryNotSet();
}
