/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVoterRegistry is IIVoterRegistry {
    function register() external;

    function deregister() external;

    function owner() external view returns (address);

    error AlreadyRegistered(address);

    error NotRegistered(address);

    error Unauthorized(address);
}
interface IIVoterRegistry {
    function isRegistered(address voter) external view returns (bool);

    function voterCount() external view returns (uint256);
}
