#!/bin/bash
set -euo pipefail

RPC_URL="${RPC_URL:-http://localhost:8547}"
PRIVATE_KEY="${PRIVATE_KEY:-0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659}"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/apps/frontend/.env.local"
WASM_DIR="$ROOT_DIR/target/wasm32-unknown-unknown/release"

# build contracts from workspace root
echo "Building contracts..."
cd "$ROOT_DIR"
rm -f "$WASM_DIR/voter_registry.wasm" "$WASM_DIR/polls.wasm"

cargo build --release --target wasm32-unknown-unknown --lib -p voter-registry
cargo build --release --target wasm32-unknown-unknown --lib -p polls

# verify the Wasm files exist and are valid contract sizes
for wasm in voter_registry.wasm polls.wasm; do
  if [ ! -f "$WASM_DIR/$wasm" ]; then
    echo "ERROR: $wasm was not produced by the build"
    exit 1
  fi
  size=$(wc -c < "$WASM_DIR/$wasm")
  if [ "$size" -lt 1000 ]; then
    echo "ERROR: $wasm is only $size bytes — build likely failed"
    exit 1
  fi
  echo "  $wasm: $size bytes"
done

# deploy voter-registry
echo ""
echo "Deploying voter-registry..."
cd "$ROOT_DIR/contracts/voter-registry"
VOTER_OUTPUT=$(cargo stylus deploy \
  --wasm-file="$WASM_DIR/voter_registry.wasm" \
  --endpoint="$RPC_URL" \
  --private-key="$PRIVATE_KEY" \
  --no-verify 2>&1) || { echo "$VOTER_OUTPUT"; exit 1; }
echo "$VOTER_OUTPUT"

VOTER_REGISTRY_ADDRESS=$(echo "$VOTER_OUTPUT" | grep "deployed code at address" | grep -oE '0x[0-9a-fA-F]{40}' | head -1)
if [ -z "$VOTER_REGISTRY_ADDRESS" ]; then
  echo "ERROR: Could not extract voter-registry address from deploy output"
  exit 1
fi
echo ""
echo "voter-registry: $VOTER_REGISTRY_ADDRESS"

# deploy polls
echo ""
echo "Deploying polls..."
cd "$ROOT_DIR/contracts/polls"
POLLS_OUTPUT=$(cargo stylus deploy \
  --wasm-file="$WASM_DIR/polls.wasm" \
  --endpoint="$RPC_URL" \
  --private-key="$PRIVATE_KEY" \
  --no-verify 2>&1) || { echo "$POLLS_OUTPUT"; exit 1; }
echo "$POLLS_OUTPUT"

POLLS_ADDRESS=$(echo "$POLLS_OUTPUT" | grep "deployed code at address" | grep -oE '0x[0-9a-fA-F]{40}' | head -1)
if [ -z "$POLLS_ADDRESS" ]; then
  echo "ERROR: Could not extract polls address from deploy output"
  exit 1
fi
echo ""
echo "polls: $POLLS_ADDRESS"

# link contracts
echo ""
echo "Linking contracts (set_registry)..."
cast send "$POLLS_ADDRESS" "setRegistry(address)" "$VOTER_REGISTRY_ADDRESS" \
  --rpc-url "$RPC_URL" \
  --private-key "$PRIVATE_KEY"

# write .env.local
echo ""
echo "Writing addresses to $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# deployed contract addresses (auto-generated by deploy script)
NEXT_PUBLIC_VOTER_REGISTRY_ADDRESS=$VOTER_REGISTRY_ADDRESS
NEXT_PUBLIC_POLLS_ADDRESS=$POLLS_ADDRESS

# local devnode rpc
DEVNODE_RPC_URL=$RPC_URL
EOF

# export ABIs
echo ""
echo "Exporting ABIs..."
cd "$ROOT_DIR/contracts/voter-registry"
cargo stylus export-abi --output "$ROOT_DIR/apps/frontend/src/abi/VoterRegistry.sol"
echo "  wrote apps/frontend/src/abi/VoterRegistry.sol"

cd "$ROOT_DIR/contracts/polls"
cargo stylus export-abi --output "$ROOT_DIR/apps/frontend/src/abi/Polls.sol"
echo "  wrote apps/frontend/src/abi/Polls.sol"

# done
echo ""
echo "Done!"
echo "  VOTER_REGISTRY: $VOTER_REGISTRY_ADDRESS"
echo "  POLLS:          $POLLS_ADDRESS"
echo "  Frontend .env.local updated"
echo "  ABIs exported to apps/frontend/src/abi/"
